---
- name: Prompt Test
  hosts: serverlocal
  vars_prompt:

   - name: greeting
     prompt: "Hello there, what is your name?"
     private: no

  tasks:

   - debug:
       msg: ' Hello: {{greeting}}'
