---
- name: Prodution OS Update
  hosts: leopard
  become: yes
  vars:
   version: v
  
  tasks:

  - name: Running the Script
    command: 
      cmd: bash /home/devops/docker-folders/VMGOS/loginpublish.sh {{version}}
