---
- name: Staging OS Update
  hosts: jaguar
  become: yes
  become_pass: "jcuc!&V3y+4]]N=w"
  
  tasks:

  - name: Running the Script
    command:
      cmd: /home/devops_ew12k542/docker-folders/VMGOS/loginpublish.sh
