---
- name: Staging OS Update
  hosts: jaguar
  become: yes
  vars:
   version: v
  
  tasks:

  - name: Running the Script
    command: sh /home/devops_ew12k542/docker-folders/VMGOS/loginpublish.sh {{version}}
